### ISSUE TITLE
rvpk on crates.io

### ISSUE THREAD

**Issue by panzi** [Daxanius/dotfiles#1]
Sorry to abuse this issue tracker to contact you.

What did I just accidentally accept on crates.io? Who are you and why did you publish rust-vpk there?

**Comment by Daxanius** [comment]
Hi,

My apologies for the sudden upload on crates, long story short I required a
way to install rvpk via cargo. I'm trying to make a cross-platform tool
which can manage some valve assets and cargo is a great way to easily
install some of these tools automatically (and cross platform) to make
things more user-friendly.

Your repository is licensed under GNU-GPL, and states one is free to
distribute it, but I kinda felt bad that I had a do it so I decided to add
you to the crate.

If you decide to update your program, I will take maintaining the update on
crates.io in my own hands unless otherwise specified.

I should have asked you this beforehand, and for that I apologize, that was
a mistake on my end.

**Comment by Daxanius** [comment]
It seems you have kicked me as crate owner. That's absolutely in your right to do, I'm just very glad it's available on crates now. Again I apologize for that

**Comment by Daxanius** [comment]
I also want to thank you for writing such a great program, it has really helped me along working with Valve assets, especially on a Linux based system. There really is a lack of tooling designed for Linux or even cross platform, which is what I'm focusing on now. Hence this (mostly personal) project

**Comment by panzi** [comment]
It just seemed very odd that someone that I don't know uploaded it to crates.io. You could just as well include some malicious code. But yes, then you wouldn't have added me as an owner to the crate. (I downloaded and diffed the code: no changes.) Anyway, since I don't know you I rather only have me being able to make a release of a software associated with my name. Not a license issue, but an issue if being under control of my own reputation. A fork published on crates.io would link to the repository of the fork, making it clear that the original author is not in control, you see. I hope you understand.
(Come to think of it, I need to investigate if I can find out if any other crate was published linking one of my GitHub repos without alerting me.)

And thank you for your kind words! It's always nice when something I wrote actually finds any use. It sure as hell is almost never the case in my actual work.
